#!/bin/sh

today=$(date +%Y-%m-%d)
yesterday=$(date +%Y-%m-%d -d yesterday)

echo ""

wget -qO- https://en.wikipedia.org/wiki/Portal:Current_events | \
	html2text -style pretty | \
	sed -n "/$today/,/$yesterday/p" | \
	head -n-2 | \
	grep -v edithistorywatch
